# This workflow will build a Java project with Maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@latest
        
    - name: Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip 
        unzip chromedriver_linux64.zip -d ChromeDriver        
        
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true

    - name: Run with Maven
      run: |
        mvn org.springframework.boot:spring-boot-maven-plugin:1.5.16.RELEASE:run &
        sleep 15

    - name: Test with Maven     
      run: mvn test